### ISSUE TITLE
mqtt hassio restart

### ISSUE THREAD

**Issue by drunkymunky** [mhwlng/fipha#2]
hi, i have a problem when restart hassio the entity created by fipha in unavailable, i need to restart fipha application to get them online, am I wrong something in the mqtt settings? thankyou

**Comment by mhwlng** [comment]
There is no auto-reconnect in this software. 
It only connects to hwinfo, mqtt and home assistant once, at startup.

It's not a small job to change this. 
I will note it as a possible future improvement.

**Comment by drunkymunky** [comment]
thankyou :)

**Comment by mhwlng** [comment]
please try version 0.0.1.0

**Comment by drunkymunky** [comment]
Now it goes perfectly, it reconnects automatically after restarting hassio, great job, thank you very much and congratulations for this application :)
