### ISSUE TITLE
Temperature sensors giving wierd unit_of_measurement

### ISSUE THREAD

**Issue by pvprodk** [mhwlng/fipha#3]
Thank you very much for this cool tool.
It is working very well, however I have a small problem with temp-sensors as shown in the image below, the unit_of_measurement for temperature sensors is Â°C  instead of °C.

![temp sensor](https://user-images.githubusercontent.com/79306514/211925099-40600283-8070-49cb-a0f4-2f1d28cf344d.png)

Any suggestions on how to fix this? Just for reference the units in hwinfo and SharedMemoryViewer looks fine:
![memory viewer](https://user-images.githubusercontent.com/79306514/211925531-9a0be746-b681-4def-bf36-c5c5b2589e7e.png)

**Comment by mhwlng** [comment]
Did you use the latest HWINFO version?  (combined with the latest version of fipha)

That should provide the data in unicode format.

If you are not using the latest HWINFO version, then see the part here about the utf-8 checkbox in windows:
https://github.com/mhwlng/fip-elite
'The UTF-8 checkbox must be enabled for non-unicode programs in the latest unicode-enabled version of HWINFO'

This is necessary for older versions of HWINFO. 

But, I thought that it was not necessary anymore for the latest HWINFO version? (combined with the latest version of fipha)

If you are already using the latest HWINFO+FIPHA, then please still try this checkbox, to see if it fixes your problem.

**Comment by pvprodk** [comment]
> If you are already using the latest HWINFO+FIPHA, then please still try this checkbox, to see if it fixes your problem.

Yes I am using latest version of HWINFO+FIPHA. Now I enabled UTF-8 and it solved the problem.
Thank you :)
