### ISSUE TITLE
Multiple machines, MQTT and "death" availability topic

### ISSUE THREAD

**Issue by EmQsed** [mhwlng/fipha#8]
Hi, i'm using fipha to monitor 2 windows systems though MQTT and home assistant and really like the new availabitly topic yet one issue arises. 
When one machine is turned off it sets all sensors to unavailable and i have to restart fipha on the machine that's on but it still show values of the turned off machine.
I'm guessing this is because of the availability topic being the same on both fipha installs and it creates a conflicts somewhere.
Is there a way to have each machine publish it's own availability status ?
I'll try to mess around with node red to remap the topic but it seems fipha can only read one death status?

**Comment by mhwlng** [comment]
I don't understand what your question is ? you have two pc's each running fpha ?

the mqtt topics should be unique for every system (it uses the pc name)
please check in mqtt explorer or some other tool

version 0.0.1.7 automatically restart the app after MqttOnConnectingFailed followed by MqttOnConnected

**Comment by EmQsed** [comment]
Yes two PCs each running fipha. When one is turned off all sensors from both PCs, even the one that's on, become unavailable. I have to restart fipha on the running PC to get the data back. And then its still show last known data for the PC that's off.
I checked MQTT explorer, all is well and every topic is unique per machine except one : homeassistant/death.
When death is not "online" it causes both instances of fipha to stop broadcasting data. So if one computer becomes offline, both stop.
Running 0.0.1.7 on both machines.
I think this is the part causing the issue.

**Comment by mhwlng** [comment]
the death mqtt topic is now prefixed by the pc name in new version 0.0.1.8

**Comment by EmQsed** [comment]
Awesome, tested and works as intended.
Thanks a lot !

**Comment by EmQsed** [comment]
After update i get messages popping on screen about fipha getting data from home assistant. These popups are always on the front and not hideable. Is there a way to fix this or make it so it would at least not be always on top ?

**Comment by mhwlng** [comment]
not sure what you mean? 

 the application is automatically restarted after MqttOnConnectingFailed followed by MqttOnConnected (it already did that in 0.0.1.7)

so something is happening on your side that makes it lose connection with home assistant?

check the application log file

**Comment by EmQsed** [comment]
Im getting this popup, it happens at startup and from time to time i guess it's reconnecting, which is ok but the window takes the priority over everything and stays on top until it's done reconnecting. 
![Capture d'écran 2024-04-24 094610](https://github.com/mhwlng/fipha/assets/20025331/3324f91b-a570-4247-9f3b-15d465236d0c)

**Comment by mhwlng** [comment]
this popup has alwas been there at startup and also at MQTT reconnect since 0.0.1.7 so it's completely unrelated to the modifications for this 'death' ticket ?

The software should not be reconnecting 'from time to time' for no reason?

Are you restarting home assisistant or disconnect your network or something like that?

Otherwise I don't know why your MQTT server is becoming unavailable 'from time to time' (whatever that means).

**Comment by EmQsed** [comment]
Thanks, i never seen this popup that's why i got curious.
Will investigate my MQTT and HA setup.
Thanks !

**Comment by mhwlng** [comment]
I will add a configuration option in appsettings.config to skip the splash screen.

**Comment by mhwlng** [comment]
version 0.0.1.9 add SplashScreen option to appsettings.config

**Comment by EmQsed** [comment]
Thank you so much !
